name: tests

on:
    push:
    pull_request:
    schedule:
        -   cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    -   php: 8.2
                        laravel: ^10.0
                        testbench: ^8.0
                    -   php: 8.2
                        laravel: ^9.0
                        testbench: ^7.0

                    -   php: 8.1
                        laravel: ^10.0
                        testbench: ^8.0
                    -   php: 8.1
                        laravel: ^9.0
                        testbench: ^7.0

                    -   php: 8.0
                        laravel: ^9.0
                        testbench: ^7.0
                    -   php: 8.0
                        laravel: ^8.0
                        testbench: ^6.0

                    -   php: 7.4
                        laravel: ^8.0
                        testbench: ^6.0
                    -   php: 7.4
                        laravel: ^7.0
                        testbench: ^5.0

                    -   php: 7.3
                        laravel: ^8.0
                        testbench: ^6.0
                    -   php: 7.3
                        laravel: ^7.0
                        testbench: ^5.0
                    -   php: 7.3
                        laravel: ^6.0
                        testbench: ^4.0
                    -   php: 7.3
                        laravel: 5.8.*
                        testbench: 3.8.*
                    -   php: 7.3
                        laravel: 5.7.*
                        testbench: 3.7.*

                    -   php: 7.2
                        laravel: ^7.0
                        testbench: ^5.0
                    -   php: 7.2
                        laravel: ^6.0
                        testbench: ^4.0
                    -   php: 7.2
                        laravel: 5.8.*
                        testbench: 3.8.*
                    -   php: 7.2
                        laravel: 5.7.*
                        testbench: 3.7.*
                    -   php: 7.2
                        laravel: 5.6.*
                        testbench: 3.6.*
                    -   php: 7.2
                        laravel: 5.5.*
                        testbench: 3.5.*

                    -   php: 7.1
                        laravel: 5.8.*
                        testbench: 3.8.*
                    -   php: 7.1
                        laravel: 5.7.*
                        testbench: 3.7.*
                    -   php: 7.1
                        laravel: 5.6.*
                        testbench: 3.6.*
                    -   php: 7.1
                        laravel: 5.5.*
                        testbench: 3.5.*

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip
                    tools: composer:v2
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                    composer update --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit --verbose
